// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute} from '@angular/router';
import swal from 'sweetalert';

import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService, ],
})
export class ArticleComponent implements OnInit {

  public article: Article;
  public url: string;

  constructor(
    public _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router,
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe( params => {
      let id = params['id'];

      this._articleService.getArticle(id).subscribe(
        response => {
          console.log(response)
          if(response.article){
            this.article = response.article;
          } else {
            this._router.navigate(['/home']);
          }
        }, 
        error => {
          console.log(error);
          this._router.navigate(['/home']);
        }
      );


    });

  }

  delete(id){
    swal({
      title: '¿Estás seguro de eliminar este artículo?',
      text: 'Una vez borrado el artículo, ¡NO PODRÁS RECUPERARLO!',
      icon: 'warning',
      buttons: ['Cancelar', 'Ok'],
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        this._articleService.delete(id).subscribe(
          response => {
            swal('Se ha borrado el artículo seleccionado', {
              icon: 'success',
            });
            this._router.navigate(['/blog']);
          },

          error => {
            console.log(error);
            this._router.navigate(['/blog']);
          }
        );

      } else {
        swal('Tranquilo, nada se ha borrado!');
      }
    });

  }

}

<div class="center">
    <section id="content">

        <article class="article-item article-detail" *ngIf="article">
            <div class="image-wrap">
                <img src="{{ url +'get-image/' +article.image }}" alt="{{ article.title }}" *ngIf="article.image">
                <img src="assets/images/no-img.jpg" alt="{{ article.title }}" *ngIf="!article.image">
            </div>

            <h1 class="subheader">{{ article.title }}</h1>

            <span class="date">
                {{ article.date | amLocale: 'es' | amTimeAgo }}
            </span>

            <p>{{ article.content }}</p>

            <div class="buttons">
                <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Eliminar</a>
            </div>
            
            <div class="clearfix"></div>
        </article>
        

    </section>

    <app-sidebar></app-sidebar>

</div>

// AprendiendoVue/src/components/Article.vue
<template>
    <div class="general">

        <div class="center">

            <section id="content">

                <div id="articles" >

                    <article class="article-item article-detail" v-if="article">
                        <div class="image-wrap">
                            <img 
                                :src=" url+'get-image/'+article.image "
                                :alt="article.title"
                                v-if="article.image"
                            />
                            <img 
                                src="../assets/image/user.png"
                                :alt="article.title"
                                v-if="!article.image"
                            />
                        </div>

                        <h1 class="subheader">{{article.title}}</h1>

                        <span class="date">
                            {{ article.date | moment( 'from', 'now', true ) }}
                        </span>

                        <p>
                            {{ article.content }}
                        </p>
                        <div class="clearfix"></div>

                        <router-link :to="'/editar-articulo/' +article._id" class="btn btn-warning">Editar</router-link>
                        <a class="btn btn-danger" @click="deleteArticle(article._id)">Borrar</a>
                    </article>

                </div>

            </section>

            <Sidebar></Sidebar>
            <div class="clearfix"></div>

        </div>

    </div>
</template>
<script>
import axios from 'axios';
import swal from 'sweetalert';
import { Global } from '../Global';

import Sidebar from './Sidebar.vue';

export default {
    name: 'Article',
    components: {
        Sidebar
    },
    data() {
        return {
            url: Global.url,
            article: null
        }
    },
    mounted(){
        let articleId = this.$route.params.id;
        this.getArticle(articleId);
    },
    methods: {
        getArticle(articleId) {
            axios.get(this.url +'article/' +articleId)
            .then( res => {

                if( res.data.status == 'success' ){

                    this.article = res.data.article;
                    console.log(this.article);

                }

            })
            .catch( error => {
                console.error(error)
            })
        },

        deleteArticle(articleId){

            swal({
                title: "Estás seguro de eliminar?",
                text: "!Una vez eliminado, no podrás recuperar el registro!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        axios.delete(this.url +'article/' +articleId)
                        .then(res => {

                            if( res.data.status == 'success' ){

                                swal( 'Artículo eliminado', 'El artículo se ha eliminado correctamente', 'success' ),
                                this.$router.push('/blog');

                            }

                        })
                        .catch(error => {
                            swal( 'Error al eliminar', 'El artículo no se ha eliminado', 'error' );
                            console.error(error)
                        })

                    } else {
                        swal("¡Tu registro ha sido conservado!");
                    }
            });

        }
    }
}
</script>
