// AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from '../../models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {

  public url: string;

  @Input() articles: Article[];

  constructor() {
    this.url = Global.url;
  }

  ngOnInit(): void {
  }

}

<div class="loading" *ngIf="!articles">
    Cargando ...
</div>

<div id="articles" *ngIf="articles">
    <article class="article-item" *ngFor="let article of articles; let i = index"> 
        <div class="image-wrap">
            <img src="{{ url +'get-image/' +article.image }}" alt="{{ article.title }}" *ngIf="article.image">
            <img src="assets/images/no-img.jpg" alt="{{ article.title }}" *ngIf="!article.image">
        </div>

        <h2>{{ i }} - {{ article.title }}</h2>
        <span class="date">
            <!-- {{ article.date | date:'dd/MM/yy HH:mm:SS' }} -->
            {{ article.date | amLocale: 'es' | amTimeAgo }}
        </span>

        <a [routerLink]="['/blog/articulo', article._id ]">Leer m&aacute;s</a>

        <div class="clearfix"></div>
    </article>
</div>

// AprendiendoVue/src/components/Articles.vue
<template>
    <div id="articles-list">

        <article class="article-item" v-for="article in articles" :key="article._id">

            <div class="image-wrap">
                <img 
                    :src=" url+'get-image/'+article.image "
                    :alt="article.title"
                    v-if="article.image"
                >
                <img 
                    src="../assets/image/user.png"
                    :alt="article.title"
                    v-if="!article.image"
                >
            </div>
                
            <h2>{{ article.title }}</h2>
            <span class="date">
                Hace 5 min
            </span>
            <a href="#">Leer m&aacute;s</a>

            <div class="clearfix"></div>
    

        </article>

    </div>

</template>
<script>
import { Global } from '../Global';

export default {
    name: 'Articles',
    props: ['articles'],
    data() {
        return {
            url: Global.url
        }
    }
}
</script>
