// AprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  public user: any;
  public campo: string;
  public campoDos: string;

  constructor() {

    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: '',
    };
  }

  ngOnInit(): void {
  }

  onSubmit(): void{
    alert('Formulario enviado');
    console.log(this.user)
  }

  hasDadoClick(): void{
    alert('Has dado click');
  }

  hasSalido(): void{
    alert('Has salido');
  }

  hasPulsado(): void{
    alert('Has pulsado enter');
  }

}

<app-slider [nombre] = "'Formularios'" [size]="'small'"></app-slider>


<div class="center">
    <section id="content">
        <h2 class="subheader">Formularios</h2>
        <form action="" class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
            
            <div class="form-group">
                <label for="nombre">Nombre : </label>
                <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" required pattern="[a-zA-Z]+"/>

                <small *ngIf="!nombre.valid && nombre.touched">
                    El nombre no es v&aacute;lido
                </small>
            </div>
    
            <div class="form-group">
                <label for="apellidos">Apellidos : </label>
                <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" required pattern="[a-zA-Z]+"/>
                <small *ngIf="!apellidos.valid && apellidos.touched">
                    Los apellidos no son v&aacute;lidos
                </small>
            </div>
        
            <div class="form-group">
                <label for="bio">Biograf&iacute;a : </label>
                <textarea name="bio" cols="30" rows="10" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
                <small *ngIf="!apellidos.valid && apellidos.touched">
                    Los bio no es v&aacute;lida
                </small>
            </div>
    
            <div class="form-group radiobuttons">
                <input type="radio" name="genero" value="hombre" #genero="ngModel" [(ngModel)]="user.genero" required/>Homber
                <input type="radio" name="genero" value="mujer"  #genero="ngModel" [(ngModel)]="user.genero" />Mujer
                <input type="radio" name="genero" value="otro"   #genero="ngModel" [(ngModel)]="user.genero" />Otro
                <small *ngIf="!genero.valid && genero.touched">
                    El g&eacute;nero no es v&aacute;lido
                </small>
            </div>
    
            <div class="clearfix"></div>
    
            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid">
    
        </form>

        <h2 class="subheader">Eventos</h2>
        <button (click)="hasDadoClick()">
            Dale Click!!!!
        </button>
        <input type="text" name="" [(ngModel)]="campo" (blur)="hasSalido()">
        {{ campo }}
        <input type="text" name="" [(ngModel)]="campoDos" (keyup.enter)="hasPulsado()">
    </section>

    <app-sidebar></app-sidebar>
 
</div>

// AprendiendoVue/src/components/Formulario.vue
<template>

    <div class="general">

        <div class="center">

            <section id="content">

                <h2 class="subheader">Formulario</h2>

                <form action="" class="mid-form" @submit.prevent="mostrarUsuario()">

                    <div class="form-group">
                        <label for="nombre">Nombre : </label>
                        <input type="text" name="nombre" v-model="user.nombre" />
                        <div v-if="submitted && !$v.user.nombre.required">
                            Este campo es requerido.
                        </div>
                        <div v-if="submitted && !$v.user.nombre.minLength">
                            Este campo debe tener más caracteres.
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="apellidos">Apellidos : </label>
                        <input type="text" name="apellidos" v-model="user.apellidos" />
                        <div v-if="submitted && !$v.user.apellidos.required">
                            Este campo es requerido.
                        </div>
                        <div v-if="submitted && !$v.user.apellidos.minLength">
                            Este campo debe tener más caracteres.
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="bio">Biograf&iacute;a : </label>
                        <textarea name="bio" cols="30" rows="10" v-model="user.bio" ></textarea>
                        <div v-if="submitted && !$v.user.bio.required">
                            Este campo es requerido.
                        </div>
                        <div v-if="submitted && !$v.user.bio.minLength">
                            Este campo debe tener más caracteres.
                        </div>
                    </div>

                    <div class="form-group radiobuttons">
                        <input type="radio" name="genero" value="hombre" checked v-model="user.genero" />Homber
                        <input type="radio" name="genero" value="mujer" v-model="user.genero" />Mujer
                        <input type="radio" name="genero" value="otro" v-model="user.genero" />Otro
                    </div>

                    <div class="clearfix"></div>

                    <input type="submit" value="Enviar" class="btn btn-success">

                </form>

                <div class="datos" v-if="user.nombre && user.apellidos">
                    <h3>{{ user.nombre +' ' +user.apellidos }}</h3>
                </div>

            </section>

            

            <Sidebar></Sidebar>
            <div class="clearfix"></div>

        </div>



    </div>
    
</template>
<script>
import { required, minLength } from 'vuelidate/lib/validators'
import Sidebar from './Sidebar.vue';

export default {

    name: 'Formulario',
    components: {
        Sidebar
    },
    validations: {

        user: {
            nombre: {
                required,
                minLength: minLength(2)
            },
            apellidos: {
                required,
                minLength: minLength(2)
            },
            bio: {
                required,
                minLength: minLength(10)
            }
        }

    },  
    data(){

        return {
            submitted: false,
            user: {
                nombre: '',
                apellidos: '',
                bio: '',
                genero: '',
            }
        }

    },
    methods:{

        mostrarUsuario(){

            console.log(this.user);
            this.submitted = true;

            this.$v.$touch();
            if( this.$v.$invalid ){
                return false;
            }

            alert('Validacion pasada');

        }

    }

}
</script>
