// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Pelicula } from '../../models/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input() pelicula: Pelicula;
  @Input() i: number;

  @Output() MarcarFavorita = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  seleccionar(event, pelicula): void{
    this.MarcarFavorita.emit({
      pelicula
    });

  }

}

<article class="article-item">
    <div class="image-wrap">
        <img src="{{ pelicula.image }}" alt="{{ pelicula.title }}">
    </div>

    <h2>{{ i }} - {{ pelicula.title }}</h2>
    <span class="date">
        Hace 5 min.
    </span>

    <span class="year" 
                        [ngClass]="{
                            'year-green': pelicula.year > 2016,
                            'year-red': pelicula.year < 2016
                        }">
        {{ pelicula.year }}
    </span>

    <a href="#">Leer m&aacute;s</a>

    <button (click)="seleccionar($event, pelicula)" >Seleccione favorita</button>
    <div class="clearfix"></div>
</article>

// AprendiendoVue/src/components/Pelicula.vue
<template>
    <article class="article-item" id="article-template">

        <div class="image-wrap">
            <img :src="pelicula.image" :alt="pelicula.title">
        </div>
        
        <h2>{{ pelicula.title}}</h2>
        <span class="date" :class="{
            yeargreen: pelicula.year >= 2015,
            yearred: pelicula.year < 2015
        }">
            {{ pelicula.year }}
        </span>
        <a href="#">Leer m&aacute;s</a>

        <input type="button"
               value="Marcar Como Favorita"
               @click="pasarFavoritaAlPadre(pelicula)"
             />

        <div class="clearfix"></div>

    </article>
</template>
<script>
export default {

    name: 'Pelicula',
    props: [ 'pelicula' ],
    mounted(){
        console.log(this.pelicula)
    },
    methods: {
        pasarFavoritaAlPadre( pelicula ){

            this.$emit('favorita', pelicula)

        }
    }
    
}
</script>
